services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: order-app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/scos
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npx prisma migrate deploy && npm run db:seed:dev && node dist/src/index.js"]

volumes:
  pgdata:
